# Generated by Django 3.1.5 on 2021-01-26 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamstatic',
            name='happiness_team_members',
        ),
        migrations.AddField(
            model_name='teamstatic',
            name='happiness_num_users',
            field=models.TextField(blank=True, verbose_name='# of Users of a Happiness Level'),
        ),
    ]
