# Generated by Django 3.1.5 on 2021-01-26 00:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=100)),
                ('team_member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMemberHappiness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('date_reported', models.DateField()),
                ('happiness_level', models.PositiveIntegerField(choices=[(1, 'Unhappy'), (2, 'Not Very Happy'), (3, 'Neither Happy Nor Unhappy'), (4, 'Happy'), (5, 'Very Happy')], db_index=True, default=5)),
                ('team_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='happiness.teammember')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
