# Generated by Django 3.1.5 on 2021-01-26 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happiness', '0002_auto_20210126_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammemberhappiness',
            name='happiness_level',
            field=models.CharField(choices=[('Unhappy', 'Unhappy'), ('Not Very Happy', 'Not Very Happy'), ('Neither Happy Nor Unhappy', 'Neither Happy Nor Unhappy'), ('Happy', 'Happy'), ('Very Happy', 'Very Happy')], db_index=True, default=5, max_length=255),
        ),
    ]
